# Generated by Django 5.0.8 on 2025-10-12 12:50

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('is_company', models.BooleanField(default=False, verbose_name='Es empresa')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RFC/ID Fiscal')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Persona/Empresa',
                'verbose_name_plural': 'Personas/Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('file', models.FileField(upload_to=documents.models.document_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Fecha del Documento')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('scanned', 'Escaneado'), ('digitized', 'Digitalizado'), ('categorized', 'Categorizado'), ('approved', 'Aprobado'), ('archived', 'Archivado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_status', models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente'), ('overdue', 'Vencido'), ('not_applicable', 'No Aplica')], default='not_applicable', max_length=20, verbose_name='Estado de Pago')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=255, null=True, verbose_name='Etiquetas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Asignados')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_documents', 'Puede ver todos los documentos'), ('can_approve_documents', 'Puede aprobar documentos')],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('scanned', 'Escaneado'), ('digitized', 'Digitalizado'), ('categorized', 'Categorizado'), ('approved', 'Aprobado'), ('archived', 'Archivado')], max_length=20, null=True, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('scanned', 'Escaneado'), ('digitized', 'Digitalizado'), ('categorized', 'Categorizado'), ('approved', 'Aprobado'), ('archived', 'Archivado')], max_length=20, verbose_name='Nuevo Estado')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='Motivo del cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Historial de Documento',
                'verbose_name_plural': 'Historial de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='documents.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='document',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.person', verbose_name='Persona/Empresa'),
        ),
    ]
