# Generated by Django 5.0.8 on 2025-10-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imported_from_folder',
            field=models.BooleanField(default=False, help_text='Indica si fue importado automáticamente desde la carpeta de monitoreo', verbose_name='Importado desde carpeta'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Nombre original del archivo antes de procesamiento', max_length=255, null=True, verbose_name='Nombre archivo original'),
        ),
    ]
