# Generated by Django 5.0.8 on 2025-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_imported_from_folder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Persona/Empresa/Departamento', 'verbose_name_plural': 'Personas/Empresas/Departamentos'},
        ),
        migrations.AddField(
            model_name='person',
            name='is_department',
            field=models.BooleanField(default=False, help_text='Marca si es un departamento interno de la empresa', verbose_name='Es departamento'),
        ),
    ]
