# Generated by Django 5.0.8 on 2025-10-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_person_options_person_is_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='applicable_persons',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las personas/empresas a las que aplica esta categoría (solo si no aplica a todas)', related_name='applicable_categories', to='documents.person', verbose_name='Personas aplicables'),
        ),
        migrations.AddField(
            model_name='category',
            name='applies_to_all',
            field=models.BooleanField(default=True, help_text='Si está marcado, esta categoría se aplicará a todas las personas/empresas', verbose_name='Aplica a todas las personas'),
        ),
        migrations.AddField(
            model_name='person',
            name='auto_create_folder',
            field=models.BooleanField(default=True, help_text='Crear carpeta automáticamente en el sistema de archivos', verbose_name='Crear carpeta automáticamente'),
        ),
        migrations.AddField(
            model_name='person',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Ruta de la carpeta asociada a esta persona/empresa', max_length=255, null=True, verbose_name='Ruta de carpeta'),
        ),
    ]
