# Generated by Django 5.0.8 on 2025-10-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_category_applicable_persons_category_applies_to_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('is_company', models.BooleanField(default=False, verbose_name='Es empresa')),
                ('is_department', models.BooleanField(default=False, help_text='Marca si es un departamento interno de la entidad', verbose_name='Es departamento')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='RFC/ID Fiscal')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('folder_path', models.CharField(blank=True, help_text='Ruta de la carpeta asociada a esta entidad', max_length=255, null=True, verbose_name='Ruta de carpeta')),
                ('auto_create_folder', models.BooleanField(default=True, help_text='Crear carpeta automáticamente en el sistema de archivos', verbose_name='Crear carpeta automáticamente')),
            ],
            options={
                'verbose_name': 'Entidad/Departamento',
                'verbose_name_plural': 'Entidades/Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='person',
        ),
        migrations.RemoveField(
            model_name='category',
            name='applicable_persons',
        ),
        migrations.AlterField(
            model_name='category',
            name='applies_to_all',
            field=models.BooleanField(default=True, help_text='Si está marcado, esta categoría se aplicará a todas las entidades', verbose_name='Aplica a todas las entidades'),
        ),
        migrations.AddField(
            model_name='category',
            name='applicable_entities',
            field=models.ManyToManyField(blank=True, help_text='Selecciona las entidades a las que aplica esta categoría (solo si no aplica a todas)', related_name='applicable_categories', to='documents.entity', verbose_name='Entidades aplicables'),
        ),
        migrations.AddField(
            model_name='document',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.entity', verbose_name='Entidad'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
