# Generated by Django 5.0.8 on 2025-10-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_entity_remove_document_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='category',
            name='value',
            field=models.CharField(default='default_category', help_text='Valor usado en nombres de archivos PDF (sin espacios ni caracteres especiales)', max_length=50, unique=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='value',
            field=models.CharField(default='default_doc_type', help_text='Valor usado en nombres de archivos PDF (sin espacios ni caracteres especiales)', max_length=50, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la entidad', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='entity',
            name='value',
            field=models.CharField(default='default_entity', help_text='Valor usado en nombres de archivos PDF (sin espacios ni caracteres especiales)', max_length=100, unique=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nombre que se muestra en los dropdowns', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada del tipo de documento', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(help_text='Nombre que se muestra en los dropdowns', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text='Nombre que se muestra en los dropdowns', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together={('category', 'value')},
        ),
    ]
